- name: Create Database container
  docker_container:
    image: postgres:9.5
    name: db
    networks:
      - name: "{{ d4s2_config.network }}"
    env: "{{ d4s2_config.env }}"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    pull: true
    state: started
    restart_policy: always
- name: Create app container
  docker_container:
    image: dukegcb/d4s2-apache
    name: web
    networks:
      - name: "{{ d4s2_config.network }}"
    env: "{{ d4s2_config.env }}"
    volumes:
      - /etc/external/:/etc/external/
    ports:
      - "80:80"
      - "443:443"
    pull: true
    state: started
    restart_policy: always
- name: Create task processor container
  docker_container:
    image: dukegcb/d4s2-apache
    name: worker
    networks:
      - name: "{{ d4s2_config.network }}"
    env: "{{ d4s2_config.env }}"
    pull: true
    state: started
    restart_policy: always
    command: python manage.py process_tasks
