- name: Login to docker registry
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
  when: docker_registry is defined
- name: Create Database container
  docker_container:
    image: postgres:9.5
    name: db
    networks:
      - name: "{{ d4s2_docker_network }}"
    env: "{{ d4s2_docker_env }}"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    pull: true
    state: started
    restart_policy: always
- name: Create app container
  docker_container:
    image: "{{ d4s2_docker_image }}"
    name: web
    networks:
      - name: "{{ d4s2_docker_network }}"
    env: "{{ d4s2_docker_env }}"
    volumes:
      - /etc/external/:/etc/external/
    ports:
      - "80:80"
      - "443:443"
    pull: true
    state: started
    restart_policy: always
- name: Create task processor container
  docker_container:
    image: "{{ d4s2_docker_image }}"
    name: worker
    networks:
      - name: "{{ d4s2_config_network }}"
    env: "{{ d4s2_config_env }}"
    pull: true
    state: started
    restart_policy: always
    command: python manage.py process_tasks
