- name: Login to docker registry
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
  when: docker_registry is defined
- name: Create Database container
  docker_container:
    image: postgres:9.5
    name: db
    networks:
      - name: "{{ d4s2_docker_network }}"
    env: "{{ d4s2_docker_env }}"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    pull: true
    state: started
    restart_policy: always
- name: Create app container
  docker_container:
    image: "{{ d4s2_docker_image }}"
    name: d4s2-app
    networks:
      - name: "{{ d4s2_docker_network }}"
    env: "{{ d4s2_docker_env }}"
    pull: true
    state: started
    restart_policy: always
- name: Create task processor container
  docker_container:
    image: "{{ d4s2_docker_image }}"
    name: worker
    networks:
      - name: "{{ d4s2_docker_network }}"
    env: "{{ d4s2_docker_env }}"
    pull: true
    state: started
    restart_policy: always
    command: python manage.py process_tasks
- name: Create reverse proxy web container
  docker_container:
    image: nginx:1.13
    name: web
    networks:
      - name: "{{ d4s2_docker_network }}"
    volumes:
      - "{{ docker_webapp.nginx_conf_dir }}{{ docker_webapp.nginx_conf_file }}:/etc/nginx/nginx.conf:ro"
      - "{{ docker_webapp.ssl_dir }}/{{ docker_webapp.ssl_cert_file }}:/etc/nginx/cert.crt:ro"
      - "{{ docker_webapp.ssl_dir }}/{{ docker_webapp.ssl_key_file }}:/etc/nginx/cert.key:ro"
    ports:
      - "80:80"
      - "443:443"
    pull: true
    state: started
    restart_policy: always
