---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

# Need mod_perl, which isn't available directly in CentOS. so install epel
- name: Install epel for mod_perl
  yum:
    name: epel-release
    state: present

- name: Install other yum dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mod_perl
    - mod_ssl
    - libapreq2
    - perl-CGI
    - perl-DBI

- name: Install development tools
  yum:
    name: "@Development Tools"
    state: present

- name: Install httpd-devel and mod_perl devel
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - perl-devel
    - perl-CPAN
    - httpd-devel
    - mod_perl-devel

- name: Install cpanm
  shell: "curl -L http://cpanmin.us | perl - App::cpanminus"

- name: Include /usr/local/bin in sudoers path
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^Defaults    secure_path'
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
    validate: '/usr/sbin/visudo -cf %s'

- name: Install modules via cpanm
  cpanm:
    name: "{{item}}"
  with_items:
    - Apache::DBI
    - Apache2::Cookie

- name: Install Catalyst dependencies via cpanm
  cpanm:
    name: "{{item}}"
  with_items:
    - DBIx::Class
    - MooseX::Daemonize

- name: Install Catalyst via cpanm
  cpanm:
    name: "{{item}}"
  with_items:
    - Catalyst::Devel
    - Task::Catalyst
    - DateTime::Format::Oracle

# this is really slow
#- name: Place www directory
#  copy:
#    src: /Users/dcl9/Code/docker/igspnet-docker/www
#    dest: /var/www
#    owner: apache
#    group: apache
#    mode: 0755

- name: Make Directory for SSL mutex
  file:
    path: /var/log/httpd/ssl_mutex
    state: directory
    mode: 0755

- name: Check if original httpd.conf has been moved
  stat: path=/etc/httpd/conf/httpd.conf.dist
  register: httpd_conf_dist_stat

- name: Print stat
  debug:
    msg: "{{ httpd_conf_dist_stat }}"

- name: Move aside original httpd.conf
  command: "mv /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.orig"
  when: httpd_conf_dist_stat.stat.exists == False

- name: Place the new httpd.conf
  file:
    src: /var/www/conf/httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    state: link

- name: Ensure ssl directories exist
  file:
    path: "/var/www/conf/{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "ssl-certs"
    - "ssl-keys"

- name: Place SSL certificate
  copy: content="../../../files/igspnet.genome.duke.edu.crt"
        dest="/var/www/conf/ssl-certs/igspnet.genome.duke.edu.crt"
        mode=400

- name: Place SSL private key
  copy: content="../../../files/igspnet.genome.duke.edu.key"
        dest="/var/www/conf/ssl-keys/igspnet.genome.duke.edu.key"
        mode=400

- name: restart apache
  systemd: state=restarted name=httpd
