---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

# Need mod_perl, which isn't available directly in CentOS. so install epel
- name: Install epel for mod_perl
  yum:
    name: epel-release
    state: present

- name: Install other yum dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mod_perl
    - mod_ssl
    - libapreq2
    - perl-CGI
    - perl-DBI

- name: Install development tools
  yum:
    name: "@Development Tools"
    state: present

- name: Install httpd-devel and mod_perl devel
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - perl-devel
    - perl-CPAN
    - httpd-devel
    - mod_perl-devel

- name: Install cpanm
  shell: "curl -L http://cpanmin.us | perl - App::cpanminus"


- name: Include /usr/local/bin in sudoers path
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^Defaults    secure_path'
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
    validate: '/usr/sbin/visudo -cf %s'

- name: Install modules via cpanm
  cpanm:
    name: "{{item}}"
  with_items:
    - Apache::DBI
    - Apache2::Cookie

- name: Install Catalyst dependencies via cpanm
  cpanm:
    name: "{{item}}"
  with_items:
    - DBIx::Class
    - MooseX::Daemonize

- name: Install Catalyst via cpanm
  cpanm:
    name: "{{item}}"
  with_items:
    - Catalyst::Devel
    - Task::Catalyst
    - DateTime::Format::Oracle
