- name: "Connecting to google cloud project {{ gcloud_project_id }}"
  command: >
    gcloud config set project
    "{{ gcloud_project_id }}"

- name: Check if provisioner exists
  command: >
    helm list | grep
    "{{ cluster_name }}"
  register: provisioner_exists_results

- name: "Removing nfs client provisioner nfsprovisioner{{ cluster_name }}"
  command: >
    helm delete --purge
    "nfsprovisioner{{ cluster_name }}"
  when: provisioner_exists_results.stdout != ""

- name: "Check if file storage named {{ filestore_name }} exists"
  command: >
    gcloud filestore instances list
    --format="value(name)"
    "--filter=name=projects/{{ gcloud_project_id }}/locations/{{ gcloud_compute_zone }}/instances/{{ filestore_name }}"
    "--zone={{ gcloud_compute_zone }}"
  register: find_filestore_result

# delete file storage that underlies the k8s persistent volume provisioner above
- name: "Deleting file storage {{ filestore_name }}"
  command: >
    gcloud filestore instances delete -q
    "{{ filestore_name }}"
    "--zone={{ gcloud_compute_zone }}"
  when: find_filestore_result.stdout != ""
