- include: tasks/gcloud_create_k8s_cluster.yml
  when: lando_k8s_state|default('present') == "present"

- include_role:
    name: bespin_k8s_cluster
    apply:
      environment:
        K8S_AUTH_API_KEY: "{{ gcloud_k8s_token }}"
        K8S_AUTH_HOST: "{{ gcloud_k8s_host }}"
        K8S_AUTH_VERIFY_SSL: no
  when: lando_k8s_state|default('present') == "present"

- include: tasks/setup_bespin_api_connection.yml
  when: lando_k8s_state|default('present') == "present"

- include: tasks/gcloud_create_file_storage.yml
  when: lando_k8s_state|default('present') == "present"


- include: tasks/disable_bespin_api_connection.yml
  when: lando_k8s_state|default('present') == "absent"

- include: tasks/gcloud_delete_file_storage.yml
  when: lando_k8s_state|default('present') == "absent"

- include: tasks/gcloud_delete_k8s_cluster.yml
  when: lando_k8s_state|default('present') == "absent"
