- name: Make SSL directory
  file: path="{{ bespin_settings.job_watcher.ssl_dir }}" state=directory

- name: Place SSL private key
  copy: src="../../../files/{{ bespin_settings.job_watcher.ssl_cert_file }}" dest="{{ bespin_settings.job_watcher.ssl_dir }}/server.crt"
        mode=400

- name: Place SSL Certificate
  copy: src="../../../files/{{ bespin_settings.job_watcher.ssl_key_file }}" dest="{{ bespin_settings.job_watcher.ssl_dir }}/server.key"
        mode=400

- name: Create directory for config
  file:
    path: /usr/src/app
    state: directory

- name: Create application configuration file
  template: src=config.j2 dest=/usr/src/app/config.json mode=400

- name: Create bespin-job-watcher container
  docker_container:
    image: "{{ bespin_settings.job_watcher.build.image_name }}:{{ bespin_settings.job_watcher.build.version }}"
    name: bespin-job-watcher
    volumes:
      - /etc/external/:/etc/external/
      - /usr/src/app/config.json:/usr/src/app/config.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    pull: true
    etc_hosts: "{{ bespin_hosts_list }}"
    state: started
    restart_policy: always
