- name: Update apt cache
  apt:
    update_cache: yes

- name: Install apt dependencies
  apt:
   name: "{{ packages }}"
  vars:
    packages:
    - nfs-common
    - libssl-dev
    - nodejs

- name: Install lando from PyPI
  pip:
    name: lando
    version: "{{ lando_version }}"
    executable: pip3
  when: lando_install_source == 'PyPI'

- name: Install lando from git
  pip:
    name: "git+git://github.com/Duke-GCB/lando.git@{{ lando_github_version }}"
    editable: false
    executable: pip3
  when: lando_install_source == 'GitHub'

- name: Check where lando_worker has been installed to
  command: which lando_worker
  register: which_lando_worker
  changed_when: no

- name: Install utility package from PyPI
  pip:
    name: "{{ util_package_name }}"
    version: "{{ util_package_version }}"
    executable: pip3

- name: Install html5lib via pip
  pip:
    name: html5lib
    executable: pip3

- name: Install CWL runner
  pip:
    name: "{{ cwl_runner }}"
    version: "{{ cwl_runner_version }}"
    executable: pip3

- name: Make lando work directory
  file:
    dest: "{{ lando_work_directory }}"
    state: directory
    owner: ubuntu
    mode: 0744

- name: Setup lando_worker service
  blockinfile:
    dest: /etc/systemd/system/lando_worker.service
    create: yes
    block: |
      [Unit]
      Description=Lando Service
      After=multi-user.target
      [Service]
      Type=idle
      ExecStart={{ which_lando_worker.stdout }}
      WorkingDirectory={{ lando_work_directory }}
      User=root
      [Install]
      WantedBy=multi-user.target

- name: Start lando_worker service
  service:
    name: lando_worker
    state: started
    enabled: yes

- name: set mountpoints
  mount:
    name: "{{ worker_mount_name }}"
    src: "{{ worker_mount_src }}"
    fstype: nfs
    opts: ro,sync,hard,intr
    state: mounted

