- name: Update apt cache
  apt: update_cache=yes

- name: Install pip
  apt: name={{item}}
  with_items:
    - python-pip
    - nfs-common

- pip:
    name: git+git://github.com/Duke-GCB/lando-messaging.git
    editable: false

- pip:
    name: git+git://github.com/Duke-GCB/lando.git
    editable: false

- pip:
    name: cwlref-runner
    editable: false

- pip:
    name: html5lib
    editable: false

- file:
    dest: /work
    state: directory
    owner: ubuntu
    mode: 0744

- name: Setup lando_worker service
  blockinfile:
    dest: /etc/systemd/system/lando_worker.service
    create: yes
    block: |
      [Unit]
      Description=Lando Service
      After=multi-user.target
      [Service]
      Type=idle
      ExecStart=/usr/local/bin/lando_worker
      WorkingDirectory=/work
      User=root
      [Install]
      WantedBy=multi-user.target

- service:
    name: lando_worker
    state: started
    enabled: yes

- name: set mountpoints
  mount:
    name: /data
    src: bespin-nfs:/mnt/bespin_datasets
    fstype: nfs
    opts: ro,sync,hard,intr
    state: mounted

