---

- name: Copy ldap.conf
  template: src=ldap.conf.j2 dest=/etc/openldap/ldap.conf owner=root group=root mode=0644

- name: Create cacert directory
  file:
    path: /etc/openldap/cacerts
    state: directory
    owner: root
    group: root
    mode: 0755
    force: no

- name: Copy OpenLDAP cert
  copy:
    src: idms-authdir.pem
    dest: /etc/openldap/cacerts/idms-authdir.pem
    owner: root
    group: root
    mode: 644
    force: no

- name: Rehash OpenLDAP Cacerts
  command: cacertdir_rehash /etc/openldap/cacerts

- name: Copy sssd conf
  action: template src=sssd.j2 dest=/etc/sssd/sssd.conf owner=root group=root mode=0600
  notify: Reload sssd

- name: Setup auth
  command: >
    authconfig --enablesssd --enablesssdauth --disableldap --disableldapauth --disablekrb5 --update

- name: sshd configuration file update
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - restart sshd

- name: sudoers configuration file update
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    backup: yes
    owner: root
    group: root
    mode: 0440

- name: copy ssh banner warning
  template:
    src: issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0444
