- name: Make Fixture directory
  file:
    path: "{{ bespin_settings.web.fixture_directory }}"
    state: directory

- name: Place fixture files
  copy:
    src: "../../../files/{{ item }}"
    dest: "{{ bespin_settings.web.fixture_directory }}/{{ item }}"
    mode: 400
  with_items: "{{bespin_settings.web.fixture_files}}"

- name: Load Fixtures
  docker_container:
    command: "python manage.py loaddata {{ bespin_settings.web.fixture_directory }}/{{ item }}"
    name: bespin-loaddata
    image: dukegcb/bespin-web
    pull: true
    state: started
    env: "{{ web_environment }}"
    volumes:
      - /etc/external/:/etc/external/
      - "{{ bespin_settings.web.fixture_directory }}:{{ bespin_settings.web.fixture_directory }}"
    etc_hosts: "{{ bespin_hosts_list }}"
  with_items: "{{bespin_settings.web.fixture_files}}"

- name: Specific Load Commands
  docker_container:
    command: "python manage.py {{ item }}"
    name: bespin-loaddata
    image: dukegcb/bespin-web
    pull: true
    state: started
    env: "{{ web_environment }}"
    volumes:
      - /etc/external/:/etc/external/
    etc_hosts: "{{ bespin_hosts_list }}"
  with_items:
    - "creategroupmanagerconnection ${GROUP_MANAGER_ACCOUNT_ID} ${GROUP_MANAGER_PASSWORD}"
    - "makelandoconnection ${RABBIT_HOST} ${RABBIT_USERNAME} ${RABBIT_PASSWORD} ${RABBIT_QUEUENAME}"
    - "makeusertoken ${LANDO_DJANGO_USERNAME} ${LANDO_DJANGO_PASSWORD} ${LANDO_DJANGO_TOKEN}"

- name: Remove loaddata container
  docker_container:
    name: bespin-loaddata
    state: absent
