# Create/Setup bespin-web docker container
# bespin_web_loaddata - loads the database associated with bespin-web with data based on bespin_settings
# bespin_web_server- creates/updates the webserver docker container

- name: Setup bespin web vars
  include_tasks: setup-environment.yml

- name: Load static data
  include_tasks: loaddata.yml
  tags: bespin_web_loaddata

- name: Run web server
  include_tasks: run-server.yml
  tags: bespin_web_server
