- set_fact:
    web_environment: "{{ web_environment|default({}) | combine(item) }}"
  with_items:
    - POSTGRES_USER: "{{ bespin_settings.database.username }}"
    - POSTGRES_PASSWORD: "{{ bespin_settings.database.password }}"
    - POSTGRES_DB: "{{ bespin_settings.database.name }}"
    - BESPIN_SECRET_KEY: "{{ bespin_settings.web.secret_key }}"
    - BESPIN_ALLOWED_HOST: "{{ bespin_settings.web.allowed_host }}"
    - BESPIN_CORS_HOST: "{{ bespin_settings.web.cors_host }}"
    - BESPIN_DB_HOST: "{{ bespin_settings.database.host }}"
    - LANDO_DJANGO_USERNAME: "{{ bespin_settings.web.lando_username }}"
    - LANDO_DJANGO_PASSWORD: "{{ bespin_settings.web.lando_password }}"
    - LANDO_DJANGO_TOKEN: "{{ bespin_settings.web.lando_token }}"
    - RABBIT_HOST: "{{ bespin_settings.rabbit.host }}"
    - RABBIT_USERNAME: "{{ bespin_settings.rabbit.username }}"
    - RABBIT_PASSWORD: "{{ bespin_settings.rabbit.password }}"
    - RABBIT_QUEUENAME: "{{ bespin_settings.rabbit.listen_queue }}"

- name: Create app container
  docker_container:
    image: quay.io/dukegcb/bespin-web
    name: bespin-web
    env: "{{ web_environment }}"
    volumes:
      - /etc/external/:/etc/external/
    ports:
      - "80:80"
      - "443:443"
    pull: true
    etc_hosts: "{{ bespin_hosts_list }}"
    state: started
    restart_policy: always
