- name: Setup bespin web vars
  include_tasks: setup-environment.yml

- name: Run fixtures
  include_tasks: run-fixtures.yml
  when: run_fixtures

- name: Run web server
  include_tasks: run-server.yml
  when: run_server
