- name: Make SSL directory
  file: path="{{ bespin_settings.web.ssl_dir }}" state=directory

- name: Place SSL private key
  copy: src="../../../files/{{ bespin_settings.web.ssl_cert_file }}" dest="{{ bespin_settings.web.ssl_dir }}/cacert.pem"
        mode=400

- name: Place SSL Certificate
  copy: src="../../../files/{{ bespin_settings.web.ssl_key_file }}" dest="{{ bespin_settings.web.ssl_dir }}/privkey.pem"
        mode=400

# The bespin-api Docker image includes apache and is configured to serve the production-built
# bespin-ui ember app from /srv/ui. That app is built by the build_ember_app, and placed in a docker volume
- name: Create app container
  docker_container:
    image: "{{ bespin_settings.web.build.image_name}}:{{ bespin_settings.web.build.version }}-apache"
    name: bespin-web
    env: "{{ web_environment }}"
    volumes:
      - /etc/external/:/etc/external/
      - "bespin-ui-{{ bespin_settings.ui.build.version }}:/srv/ui/:ro"
    ports:
      - "80:80"
      - "443:443"
    etc_hosts: "{{ bespin_hosts_list }}"
    state: started
    restart_policy: always
