- name: Make SSL directory
  file: path="{{ bespin_settings.web.ssl_dir }}" state=directory

- name: Place SSL private key
  copy: src="../../../files/{{ bespin_settings.web.ssl_cert_file }}" dest="{{ bespin_settings.web.ssl_dir }}/cacert.pem"
        mode=400

- name: Place SSL Certificate
  copy: src="../../../files/{{ bespin_settings.web.ssl_key_file }}" dest="{{ bespin_settings.web.ssl_dir }}/privkey.pem"
        mode=400

# The bespin-api Docker image includes apache and is configured to serve the production-built
# bespin-ui ember app from /srv/ui. The app is built using the build_ember_app role and should be placed
# in bespin_settings.ui.srv_dir
# That directory is mounted as a volume, so we can't simply delete / replace the directory otherwise
# docker and apache can't find it.
- name: Ensure directory exists for bespin-ui
  file:
    state: directory
    path: "{{ bespin_settings.ui.srv_dir }}"

- name: Create app container
  docker_container:
    image: "{{ bespin_settings.web.build.image_name}}:{{ bespin_settings.web.build.version }}-apache"
    name: bespin-web
    env: "{{ web_environment }}"
    volumes:
      - /etc/external/:/etc/external/
      - "{{ bespin_settings.ui.srv_dir }}:/srv/ui/"
    ports:
      - "80:80"
      - "443:443"
    etc_hosts: "{{ bespin_hosts_list }}"
    state: started
    restart_policy: always
