---
# This role uses individual docker <noun> prune commands
# rather than `docker system prune`, since we do not want to
# remove volumes, networks, or build cache

# First remove all stopped containers to free up images
# that are only used by stopped containers
- name: Prune stopped containers
  command: "docker container prune"
  when: prune_containers

# Now remove all images not used by a container
- name: Prune unused images
  command: "docker image prune -a"
  when: prune_images
