- name: Allow password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication yes"

- name: Restart sshd
  systemd:
    state: restarted
    name: sshd

- name: Add a workshop user
  user:
    name: "{{ workshop_user }}"
    password: "{{ [workshop_user, 'password'] | join('-') | password_hash('sha512') }}"


# TODO: Report the users and IP addresses
