- name: Install apache2 packages
  apt: name={{item}}
  with_items:
    - apache2

- git:
    repo: https://github.com/Duke-GCB/bespin-ui.git
    dest: /src/bespin-ui
    force: yes
  become: Yes
  become_user: ubuntu

- file:
    path: /src/bespin-ui
    owner: ubuntu
    state: directory
    recurse: yes
    mode: 0755

- name: install bower
  command: npm install -g bower

- name: install ember-cli
  command: npm install -g ember-cli

- name: install npm packages
  command: npm install
  args:
    chdir: /src/bespin-ui
    creates: /tmp/bespin-ui/node_modules

- name: install bower packages
  command: bower install
  become: Yes
  become_user: ubuntu
  args:
    chdir: /src/bespin-ui
    creates: /tmp/bespin-ui/bower_components

- name: Setup api server config
  become: Yes
  become_user: ubuntu
  lineinfile:
    dest: /src/bespin-ui/config/environment.js
    regexp: 'ENV.APP.API_HOST = '
    line: "    ENV.APP.API_HOST = 'http://{{ bespin_settings.api.host }}',"
    insertafter: "if (environment === 'production') {"

- name: build bespin ui
  command: ember build --environment production
  become: Yes
  become_user: ubuntu
  args:
    chdir: /src/bespin-ui

- name: copy ember website
  command: 'bash -c "cp -r /src/bespin-ui/dist/* /var/www/html"'

- name: enable apache mod_rewrite
  command: a2enmod rewrite

- name: setup minimal document root
  copy:
    dest: /etc/apache2/sites-available/ember.conf
    content: |
      DocumentRoot /var/www
      <Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
      </Directory>

- name: setup .htaccess rewrite rule
  copy:
    dest: /var/www/html/.htaccess
    content: |
      <IfModule mod_rewrite.c>
      RewriteEngine On
      RewriteRule ^index\.html$ - [L]
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule (.*) index.html [L]
      </IfModule>

- name: enable ember website
  command: a2ensite ember.conf

- service:
    name: apache2
    state: restarted
    enabled: yes
