- set_fact:
    ca_cert_filename: ""

- set_fact:
    ca_cert_filename: "{{ ca_certificates_dir }}/lando_k8s_ca.crt"
  when: item.ssl_ca_cert_data is defined

- name: Assure ca certificates directory exists
  file:
    path: "{{ ca_certificates_dir }}"
    state: directory

- name: Place ca certificate
  copy: content="{{ item.ssl_ca_cert_data }}" dest="{{ ca_cert_filename}}"
  when: item.ssl_ca_cert_data is defined

- name: "Setup lando config {{ lando_config_path }}"
  template:
    src: lando_k8s_config.yml.j2
    dest: "{{ lando_config_path }}"

- name: "Create {{ k8s_cluster_name }} lando kubernetes job runner container"
  docker_container:
    image: "{{ bespin_settings.lando.build.image_name }}:{{ bespin_settings.lando.build.version }}"
    name: "bespin-lando-k8s-{{ k8s_cluster_name }}"
    volumes:
      - "{{ lando_config_path }}:{{ lando_config_path }}:ro"
      - "{{ ca_certificates_dir }}:{{ ca_certificates_dir }}:ro"
    etc_hosts: "{{ bespin_hosts_list }}"
    state: started
    restart_policy: always
    command: python -m lando.k8s.lando "{{ lando_config_path }}"

- name: "Create {{ k8s_cluster_name }} lando kubernetes watcher container"
  docker_container:
    image: "{{ bespin_settings.lando.build.image_name }}:{{ bespin_settings.lando.build.version }}"
    name: "bespin-watcher-k8s-{{ k8s_cluster_name }}"
    volumes:
      - "{{ lando_config_path }}:{{ lando_config_path }}:ro"
      - "{{ ca_certificates_dir }}:{{ ca_certificates_dir }}:ro"
    etc_hosts: "{{ bespin_hosts_list }}"
    state: started
    restart_policy: always
    command: python -m lando.k8s.watcher "{{ lando_config_path }}"
