- name: Create lando k8s services for each item in bespin_settings.k8s_clusters
  include_tasks: create-services.yml
  vars:
    k8s_cluster_name: "{{ item.key }}"
    lando_config_path: "/etc/lando_{{ item.key }}_config.yml"
    lando_k8s: "{{ item.value }}"
  with_dict:  "{{ bespin_settings.k8s_clusters }}"
