---
- name: Install software from yum
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - man
    - git
    - zip
    - unzip
    - tcsh
    - evince
    - firefox
    - gedit
    - gedit-plugins
    - inkscape
    - ImageMagick
    - mesa-libGL
    - mesa-libGLU
    - java-1.8.0-openjdk-headless
    - python-pip
    - nfs-utils
    - R
    - samtools
# for ansible >=2.4, use allow_downgrade and specify versions for R and samtools
- name: Install cran packages for R
  become: yes
  command: /usr/bin/Rscript -e "install.packages(pkgs='ggplot2', repos=c('http://archive.linux.duke.edu/cran/'))"
- name: Install bioconductor packages for R
  become: yes
  command: /usr/bin/Rscript -e "source('http://bioconductor.org/biocLite.R'); biocLite('DESeq2')"
- name: Install STAR
  become: yes
  git:
    repo: 'https://github.com/alexdobin/STAR.git'
    dest: /opt/STAR
    version: 2.5.3a
- name: Symlink STAR
  file: src=/opt/STAR/bin/Linux_x86_64/STAR dest=/usr/local/bin/STAR state=link
- name: symlink STARlong
  file: src=/opt/STAR/bin/Linux_x86_64/STARlong dest=/usr/local/bin/STARlong state=link
- name: Download and unpack IGV
  unarchive:
    src: http://data.broadinstitute.org/igv/projects/downloads/IGV_2.3.97.zip
    dest: /opt
    remote_src: yes
- name: Download and unpack fastQC
  unarchive:
    src: http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.4.zip
    dest: /opt
    remote_src: yes
- name: Make fastqc wrapper executable
  file:
    path: /opt/FastQC/fastqc
    mode: 0755
- name: Update PATH for all users to include /opt/FastQC
  file: path=/etc/profile.d/fastqc.sh state=touch mode=0755
- copy: content="export PATH=/opt/FastQC:$PATH" dest=/etc/profile.d/fastqc.sh
- name: Install cutadapt
  pip:
    name: cutadapt
    version: 1.14
- name: Create TrimGalore directory
  file: path=/opt/TrimGalore state=directory mode=0755
- name: Install TrimGalore!
  unarchive:
    src: http://www.bioinformatics.babraham.ac.uk/projects/trim_galore/trim_galore_v0.4.4.zip
    dest: /opt/TrimGalore
    remote_src: yes
- name: Symlink trim_galore
  file: src=/opt/TrimGalore/trim_galore dest=/usr/local/bin/trim_galore state=link
- name: Create NFS directory
  file: path=/nfs/data state=directory mode=0755 recurse=yes
- name: mount /nfs/data
  mount: fstype=nfs opts='vers=3' path=/nfs/data src={{ readonly }} state=mounted
- name: Create GSEA directory
  file: path=/opt/GSEA state=directory mode=0755
- name: Symlink GSEA jar file to /opt/GSEA/gsea-3.0.jar
  file: src=/nfs/data/GSEA/gsea-3.0.jar dest=/opt/GSEA/gsea-3.0.jar state=link

