---
- name: Install software from yum
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - man
    - git
    - zip
    - unzip
    - tcsh
    - evince
    - firefox-38.7.0-1.el7_2
    - xorg-x11-xauth
    - xorg-x11-apps
    - xorg-x11-xinit
    - gedit
    - gedit-plugins
    - inkscape
    - ImageMagick
    - mesa-libGL
    - mesa-libGLU
    - java-1.8.0-openjdk
    - python-pip
    - python-devel
    - nfs-utils
    - libxml2-devel
    - curl-devel
    - R
    - samtools
# for ansible >=2.4, use allow_downgrade and specify versions for R and samtools
- name: Exclude firefox from yum updates
  become: yes
  lineinfile:
    dest: /etc/yum.conf
    insertafter: '^installonly_limit='
    line: 'exclude=firefox*'
- name: Fix sshd_config for X11UseLocalhost
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#X11UseLocalhost'
    line: 'X11UseLocalHost no'
- name: Fix sshd_config for X11DisplayOffset
  become: yes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#X11DisplayOffset'
    line: 'X11DisplayOffset 10'
- name: Install cran packages for R
  become: yes
  command: /usr/bin/Rscript -e "install.packages(pkgs=c('ggplot2', 'gplots'), repos=c('http://archive.linux.duke.edu/cran/'))"
- name: Install bioconductor packages for R
  become: yes
  command: /usr/bin/Rscript -e "source('http://bioconductor.org/biocLite.R'); biocLite('DESeq2')"
- name: Install QoRTs R package
  become: yes
  command: /usr/bin/Rscript -e "install.packages('http://hartleys.github.io/QoRTs/QoRTs_STABLE.tar.gz',repos=NULL,type='source');"
- name: Install STAR
  become: yes
  git:
    repo: 'https://github.com/alexdobin/STAR.git'
    dest: /opt/STAR
    version: 2.5.3a
- name: Symlink STAR
  become: yes
  file: src=/opt/STAR/bin/Linux_x86_64/STAR dest=/usr/local/bin/STAR state=link
- name: symlink STARlong
  become: yes
  file: src=/opt/STAR/bin/Linux_x86_64/STARlong dest=/usr/local/bin/STARlong state=link
- name: Download and unpack IGV
  become: yes
  unarchive:
    src: http://data.broadinstitute.org/igv/projects/downloads/2.3/IGV_2.3.97.zip
    dest: /opt
    remote_src: yes
- name: Download and unpack fastQC
  become: yes
  unarchive:
    src: http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.4.zip
    dest: /opt
    remote_src: yes
- name: Make fastqc wrapper executable
  become: yes
  file:
    path: /opt/FastQC/fastqc
    mode: 0755
- name: Update PATH for all users to include /opt/FastQC
  become: yes
  blockinfile:
    create: yes
    path: /etc/profile.d/fastqc.sh
    mode: 0644
    block: export PATH=/opt/FastQC:$PATH
- name: Upgrade pip
  become: yes
  pip:
    name: pip
    extra_args: --upgrade
- name: Install cutadapt
  become: yes
  pip:
    name: cutadapt
    version: 1.14
- name: Install development version of MultiQC
  become: yes
  pip:
    name: multiqc
- name: Install HTSeq
  become: yes
  pip:
    name: HTSeq
- name: Create TrimGalore directory
  become: yes
  file: path=/opt/TrimGalore state=directory mode=0755
- name: Install TrimGalore!
  become: yes
  unarchive:
    src: http://www.bioinformatics.babraham.ac.uk/projects/trim_galore/trim_galore_v0.4.4.zip
    dest: /opt/TrimGalore
    remote_src: yes
- name: Symlink trim_galore
  become: yes
  file: src=/opt/TrimGalore/trim_galore dest=/usr/local/bin/trim_galore state=link
- name: Create NFS directory
  become: yes
  file: path=/nfs/data state=directory mode=0755
- name: mount /nfs/data
  become: yes
  mount: fstype=nfs opts='vers=3' path=/nfs/data src={{ readonly }} state=mounted
- name: Create GSEA directory
  become: yes
  file: path=/opt/GSEA state=directory mode=0755
- name: Symlink GSEA jar file to /opt/GSEA/gsea-3.0.jar
  become: yes
  file: src=/nfs/data/bin/GSEA3/gsea-3.0.jar dest=/opt/GSEA/gsea-3.0.jar state=link
- name: Create QoRTs directory
  become: yes
  file: path=/opt/QoRTs state=directory mode=0755
- name: Install QoRTs .jar file
  become: yes
  get_url:
    url: http://hartleys.github.io/QoRTs/QoRTs-STABLE.jar
    dest: /opt/QoRTs/QoRTs-STABLE.jar
    mode: 0555
- name: Create /work directory
  become: yes
  file: path=/work state=directory mode=0777 recurse=yes
