- name: Ensure directory exists for cloning git repo
  file:
    state: directory
    path: "{{ local_repo_path }}/{{ image_name }}-{{ version }}"

# Note that this checks out the git repo to the provided local repo
# path and image name. it does not infer a subdirectory name from the
# remote git repo like the default git mode.
# We must use a somewhat unique name here so that one host can
# support different image builds
- name: Clone the Git repo at the provided version
  git:
    repo: "{{ repo_path }}"
    dest: "{{ local_repo_path }}/{{ image_name }}-{{ version }}"
    version: "{{ version }}"

# TODO: Only build the docker image if the git version changed.
- name: Build a docker image
  docker_image:
    path: "{{ local_repo_path }}/{{ image_name }}-{{ version }}"
    name: "{{ image_name }}"
    tag: "{{ version }}"
