- name: Creates predictions data directory shared by portal and worker
  file: path="{{ imads.data_root }}/pred_data" state=directory

- name: Creates models directory
  file: path="{{ imads.data_root }}/pred_data/models" state=directory

- name: Creates work directory
  file: path="{{ imads.data_root }}/pred_data/work" state=directory mode="a+rwx"

# Create database
- include: tasks/setup_postgres.yml

- include: tasks/setup_portal.yml

- include: tasks/setup_vacuum.yml

- include: tasks/setup_worker.yml
