# Daemon that purges database records after certain time periods.

- name: Create database vacuum container
  docker_container:
    image: "{{ imads.web.build.image_name }}:{{ imads.web.build.version }}"
    name: vacuum
    networks:
      - name: "{{ imads.network }}"
    env: "{{ imads.env }}"
    command: python vacuum.py 2880
    volumes:
      - "{{ imads.data_root }}/etc/external/:/etc/external/"
      - "{{ imads.data_root }}/pred_data:/tmp/pred_data"
    pull: false
    state: started
    restart_policy: always
