# Daemon that purges database records after certain time periods.

- name: Create database vacuum container
  docker_container:
    image: dukegcb/imads
    name: vacuum
    networks:
      - name: "{{ imads.network }}"
    env: "{{ imads.env }}"
    command: python vacuum.py 2880
    volumes:
      - /etc/external/:/etc/external/
      - "{{ imads.data_root }}/pred_data:/tmp/pred_data"
    pull: true
    state: started
    restart_policy: always
