# Runs webserver that reads database and sends jobs to worker daemon.

- name: Create web portal container
  docker_container:
    image: "{{ imads_web.build.image_name }}:{{ imads_web.build.version }}"
    name: web
    networks:
      - name: "{{ imads.network }}"
    env: "{{ imads.env }}"
    volumes:
      - "{{ imads.data_root }}/etc/external/ssl/:/etc/external/ssl/"
      - "{{ imads.data_root }}/pred_data:/tmp/pred_data"
    ports:
      - "80:80"
      - "443:443"
    pull: false
    state: started
    restart_policy: always
