- include: tasks/create_k8s_cluster.yml
- include: tasks/get-kubeconfig-credentials.yml
- include_role:
    name: bespin_k8s_namespace
    apply:
      environment: "{{ k8s_auth_env }}"
- include: tasks/create_file_storage.yml
  environment: "{{ k8s_auth_env }}"
- include: tasks/update_bespin_api_connection.yml
