- name: "Creating k8s cluster {{ cluster_name }} in zone {{ gcloud_compute_zone }}"
  command: >
    gcloud container clusters create "{{ cluster_name }}"
    --zone "{{ gcloud_compute_zone }}"
    --machine-type "{{ gcloud_machine_type }}"
    --enable-autoscaling
    --no-enable-autoupgrade
    --num-nodes "{{ gcloud_num_nodes }}"
    --min-nodes "{{ gcloud_min_nodes }}"
    --max-nodes "{{ gcloud_max_nodes }}"
  when: not cluster_exists

- name: Create the large-machine-pool node pool
  command: >
    gcloud container node-pools create large-machine-pool
    --cluster {{ cluster_name }}
    --zone {{ gcloud_compute_zone }}
    --enable-autoscaling
    --machine-type {{ large_pool_machine_type }}
    --num-nodes {{ large_pool_num_nodes }}
    --min-nodes {{ large_pool_min_nodes }}
    --max-nodes {{ large_pool_max_nodes }}
  when: not large_node_pool_exists
