- include: tasks/update_bespin_api_connection.yml
- include: tasks/get-service-account-credentials.yml
  when: cluster_exists
- include_role:
    name: bespin_k8s_namespace
    apply:
      environment: "{{ gcloud_k8s_env }}"
  when: cluster_exists
- include: tasks/delete_file_storage.yml
  environment: "{{ gcloud_k8s_env }}"
- include: tasks/delete_k8s_cluster.yml