- include: tasks/update_bespin_api_connection.yml
- include: tasks/get-service-account-credentials.yml
  when: cluster_exists
- include_role:
    name: bespin_k8s_cluster
    apply:
      environment:
        K8S_AUTH_API_KEY: "{{ gcloud_k8s_token }}"
        K8S_AUTH_HOST: "{{ gcloud_k8s_host }}"
        K8S_AUTH_VERIFY_SSL: "{{ gcloud_k8s_verify_ssl }}"
  when: cluster_exists
- include: tasks/delete_file_storage.yml
- include: tasks/delete_k8s_cluster.yml