- name: create temporary kubeconfig file
  tempfile:
    state: file
    suffix: temp
  register: kubeconfig_temp_file

- set_fact:
    kubeconfig_temp_file_path: "{{ kubeconfig_temp_file.path }}"

- name: Configure kubectl (kubeconfig) command line access to the cluster
  command: >
    gcloud container clusters get-credentials
    "{{ cluster_name }}"
    "--zone={{ gcloud_compute_zone }}"
    --project bespin-dev
  environment:
    KUBECONFIG: "{{ kubeconfig_temp_file_path }}"

- set_fact:
    k8s_auth_env:
      K8S_AUTH_KUBECONFIG: "{{ kubeconfig_temp_file_path }}"

- name: Run a kubectl command to populate the access-token in our config file
  # This is necessary to prevent 'Could not automatically determine credentials' errors when using the k8s ansible module
  # `gcloud container clusters get-credentials` does not fill in the access-token field running any kubectl command
  # will populate `access-token` in kubeconfig
  command: >
    kubectl get namespaces
    "--kubeconfig={{ kubeconfig_temp_file_path }}"