- name: Install v3.6.6 rabbitmq from their site since standard repositories rabbitmq-server is really out of date
  apt:
    deb: https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.6/rabbitmq-server_3.6.6-1_all.deb
    state: present
- rabbitmq_user: user="{{bespin_rabbit.username}}"
                 password="{{bespin_rabbit.password}}"
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
- rabbitmq_user: user="{{bespin_rabbit.worker_username}}"
                 password="{{bespin_rabbit.worker_password}}"
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
