- name: Update apt cache
  apt: update_cache=yes

- name: Install apache2 packages
  apt: name={{item}}
  with_items:
    - python-pip
    - python-psycopg2
    - apache2
    - libapache2-mod-wsgi

- git:
    repo: https://github.com/Duke-GCB/bespin-api.git
    dest: /srv/bespin_api

- pip:
    requirements: /srv/bespin_api/requirements.txt

