- name: Setup lando config
  template:
    src: lando_config.yml.j2
    dest: /etc/lando_config.yml

- name: Create app container
  docker_container:
    image: "dukegcb/bespin-lando:{{ bespin_settings.lando.version }}"
    name: bespin-lando
    volumes:
      - /etc/lando_config.yml:/etc/lando_config.yml
    pull: true
    etc_hosts: "{{ bespin_hosts_list }}"
    state: started
    restart_policy: always
