- name: Setup lando config
  template:
    src: lando_config.yml.j2
    dest: /etc/lando_config.yml

- name: Create app container
  docker_container:
    image: "{{ bespin_settings.lando.build.image_name }}:{{ bespin_settings.lando.build.version }}"
    name: bespin-lando
    volumes:
      - /etc/lando_config.yml:/etc/lando_config.yml
    etc_hosts: "{{ bespin_hosts_list }}"
    state: started
    restart_policy: always
